Bump ansible-lint to v25.8.1 (last release)
This is required because the old version currently used fails with

ModuleNotFoundError: No module named 'ansible.parsing.yaml.constructor'