Bump ansible-lint to v25.9.2 and actions to v6
This is required as current version fails on

RuntimeError: Python 3.14 requires ansible-core version >= 2.20.0, and we found 2.19.3.